Use approved PSR-15
equip/dispatch pull request #13
Opened 2018-01-23 04:21 UTC by tuupola

This PR switches to the approved version of PSR-15.

2018-01-23 04:26 UTC, tuupola commented
Build with 7.2 and nightly fails but the warnings seem not to be related to this PR. Something to do with `eloquent/phony` instead.

2018-01-23 15:02 UTC, shadowhand requested changes
If you rebase this to `master` branch it will fix the build.

2018-01-23 15:02 UTC, shadowhand commented on src/Handler.php
> +use Psr\Http\Server\RequestHandlerInterface;
This should go after `Psr\Http\Message` for alphabetical listing.

2018-01-23 15:02 UTC, shadowhand commented on src/HandlerProxy.php
> +use Psr\Http\Server\RequestHandlerInterface;
Also here and elsewhere.

2018-01-23 15:02 UTC, shadowhand commented on tests/TestCase.php
> +use Psr\Http\Server\MiddlewareInterface;
Again, alpha ordering of `use` statements.

2018-01-23 15:52 UTC, tuupola commented
Uh. Somehow I failed the rebase and did normal merge from master with fixed conflict.  The extra commit message could be hidden with squash merging the PR if needed?

2018-01-23 16:18 UTC, shadowhand approved these changes

2018-01-23 16:18 UTC, shadowhand commented
Thanks. I'll try to get this merged in later today and tagged.

2018-01-23 16:22 UTC, tuupola commented
Super. Thanks!

2018-01-26 14:37 UTC, merged

2018-01-26 14:38 UTC, shadowhand commented
Tagged as version 2.0.0